name: lt_online
description: Fitness application for workout tracking.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^0.2.12
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  flutter_dotenv: ^5.0.2
  json_serializable: ^6.1.4
  freezed: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
  
flutter:
  assets:
    - .env

  uses-material-design: true
